gdcdictionary/schemas/slide.yaml

r? @allisonheath 
https://jira.opensciencedatacloud.org/browse/DAT-93

feat(slide): reclassified to biospecimen category

---

gdcdictionary/schemas/read_group.yaml

r? @allisonheath @msfitzsimons 
https://jira.opensciencedatacloud.org/browse/DM-12

fix(rg): added HiSeq 4K instument model

---

gdcdictionary/schemas/biospecimen_supplement.yaml
gdcdictionary/schemas/clinical_supplement.yaml

r?
@allisonheath 
https://jira.opensciencedatacloud.org/browse/PGDC-2604
https://jira.opensciencedatacloud.org/browse/DAT-98

feat(clinical_sup): added new data formats

---

gdcdictionary/schemas/read_group.yaml

r? @allisonheath @millerjs @msfitzsimons 
https://jira.opensciencedatacloud.org/browse/DM-15

feat(readgroup): category for rg now biospecimen

---

gdcdictionary/schemas/analyte.yaml

r? @allisonheath @dankolbman 
https://jira.opensciencedatacloud.org/browse/DAT-170

DAT-170:feat(new ocg analytes)

---

gdcdictionary/schemas/demographic.yaml

r? @allisonheath 
https://jira.opensciencedatacloud.org/browse/DAT-34

DAT-34 feat(demographic): unrequired year of birth

---

gdcdictionary/schemas/slide_image.yaml

DAT-204 fix(slide_image): new experimental strategy description

---

gdcdictionary/schemas/analyte.yaml

r? @allisonheath @sergeymk @dankolbman

DAT-255 feat(analyte): unrequired analyte type id

---

gdcdictionary/schemas/biospecimen_supplement.yaml
gdcdictionary/schemas/clinical_supplement.yaml

DAT-225 feat(supp): added FoundationOne XML format

---

gdcdictionary/schemas/sample.yaml

r? @allisonheath @dankolbman 
https://jira.opensciencedatacloud.org/browse/DAT-233

DAT-233 feat(sample): sample_type_id not required

---

gdcdictionary/schemas/slide.yaml

DAT-205 feat(slide): new link to sample

---

gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/exposure.yaml

r? @allisonheath @msfitzsimons @sergeymk @tlicht3

DAT-108 feat(exposure): added new property and term for pack years smoked

---

.gitignore

r? @dankolbman @allisonheath 
Updated the gitginore per Ray's email.

feat(gitignore): updated gitignore

---

gdcdictionary/schemas/sample.yaml

r? @dankolbman @allisonheath @sergeymk

DAT-328 feat(sample): link to tss

---

gdcdictionary/schemas/project.yaml

Addresses [API-143](https://jira.opensciencedatacloud.org/browse/API-143)
r? @sameerageorge @dmiller15

feat(project): add intented_release_date

---

gdcdictionary/schemas/slide.yaml

nonexclusive required links
r? @dankolbman 
Can I get a quick review? @msfitzsimons and I noticed this error yesterday for https://jira.opensciencedatacloud.org/browse/DAT-205

fix(slide): unrequired portion link

---

gdcdictionary/schemas/project.yaml

Addresses [API-157](https://jira.opensciencedatacloud.org/browse/API-157).

feat(project): releasable

---

gdcdictionary/schemas/sample.yaml

r? @allisonheath @msfitzsimons @tlicht3 
Anyone have any better ideas for the "label"?
https://jira.opensciencedatacloud.org/browse/DM-13

DAT-214 feat(sample): added non-required link to diagnosis

---

gdcdictionary/examples/valid/clinical_test.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/clinical_test.yaml

r? @allisonheath @tlicht3 @msfitzsimons @dankolbman 
https://jira.opensciencedatacloud.org/browse/DAT-223
Only the properties for BLGSP are in for the time being.

DAT-223 feat(node): new node to capture biomarker information

---

gdcdictionary/examples/valid/genomic_profile_harmonization_workflow.json
gdcdictionary/examples/valid/structural_variation.json
gdcdictionary/examples/valid/submitted_genomic_profile.json
gdcdictionary/schemas/aggregated_somatic_mutation.yaml
gdcdictionary/schemas/copy_number_segment.yaml
gdcdictionary/schemas/genomic_profile_harmonization_workflow.yaml
gdcdictionary/schemas/simple_somatic_mutation.yaml
gdcdictionary/schemas/somatic_aggregation_workflow.yaml
gdcdictionary/schemas/somatic_annotation_workflow.yaml
gdcdictionary/schemas/structural_variation.yaml
gdcdictionary/schemas/submitted_genomic_profile.yaml

r? @allisonheath @ZhenyuZ @msfitzsimons @dankolbman

DAT-229 feat(FMI): added FMI nodes and updated others

---

gdcdictionary/examples/valid/case.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/case.yaml

Adds `disease_type` and `primary_site` to case.
r? @dmiller15

DAT-295 Add case properties

---

gdcdictionary/schemas/annotation.yaml
gdcdictionary/schemas/sample.yaml
gdcdictionary/schemas/tag.yaml

DAT-797 feat(type): got rid of type string with enums

---

gdcdictionary/schemas/_terms.yaml

DAT-794 fix(terms): changed term_urls for cdebrowswer5.X

---

gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/TT-68
r? @ProfOak

TT-68 feat(sample): new OCG sample_types/ids

---

gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/TT-77
r?

TT-77 feat(sample): tumor to sample_type

---

gdcdictionary/schemas/read_group.yaml

r?
https://jira.opensciencedatacloud.org/browse/TT-76

TT-76 feat(rg): targeted sequencing to strategy

---

gdcdictionary/examples/valid/treatment.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/treatment.yaml

TT-66 feat(TT-66): added regimen or line of therapy to treatment

---

gdcdictionary/examples/valid/demographic.json
gdcdictionary/schemas/demographic.yaml

feat(TT-83): updated demographic example for testing
r? @ProfOak

TT-83 feat(TT-83): added props to demographic for MMRF

---

gdcdictionary/examples/valid/case.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/case.yaml

TT-84 feat(TT-84): added properties to case

---

gdcdictionary/schemas/sample.yaml

TT-85 feat(TT-85): new OCG tumor code and id

---

gdcdictionary/schemas/read_group.yaml

TT-9 feat(TT-9): added new options for library selection

---

gdcdictionary/schemas/copy_number_segment.yaml

TT-94 feat(TT-94): new data type to copy number seg node

---

gdcdictionary/schemas/genomic_profile_harmonization_workflow.yaml

DAT-985 feat(DAT-985): new workflow types for FMI

---

gdcdictionary/schemas/diagnosis.yaml

DAT-203 feat(DAT-203): unrequire classification of tumor

---

gdcdictionary/schemas/follow_up.yaml

fix(follow_up) : semicolon to colon

---

gdcdictionary/schemas/_terms.yaml

Woot spelling. Not very important.

Spelling is hard. URL works

---

gdcdictionary/schemas/sample.yaml

Would break submissions. Good catch @wwysoc2 !

Remove unicode char for dash

---

gdcdictionary/schemas/submitted_genomic_profile.yaml

https://jira.opensciencedatacloud.org/browse/TT-75

TT-75: sgp one_to_many with rg

---

gdcdictionary/examples/valid/sample.json
gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/TT-261

TT-261: sample to sample edge for HCMI

---

gdcdictionary/schemas/structural_variation.yaml

https://jira.opensciencedatacloud.org/browse/TT-207

TT-207: updated sv node for new harmonization workflows

---

gdcdictionary/examples/valid/structural_variant_calling_workflow.json
gdcdictionary/schemas/structural_variant_calling_workflow.yaml

https://jira.opensciencedatacloud.org/browse/TT-270

TT-270: added structural variant calling workflow node

---

gdcdictionary/schemas/slide_image.yaml

https://jira.opensciencedatacloud.org/browse/TT-262

TT-262: updated slide image node for HCMI

---

gdcdictionary/examples/valid/analyte.json
gdcdictionary/schemas/analyte.yaml

https://jira.opensciencedatacloud.org/browse/TT-259

TT-259: created link from analyte to sample

---

gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/TT-258

TT-258: new sample compositions for HCMI

---

gdcdictionary/schemas/somatic_annotation_workflow.yaml

https://jira.opensciencedatacloud.org/browse/TT-216

TT-216: added pindel annotation workflow type

---

gdcdictionary/schemas/clinical_supplement.yaml

https://jira.opensciencedatacloud.org/browse/TT-271

TT-271: new clinical supplement format for CDC

---

gdcdictionary/schemas/rna_expression_workflow.yaml

https://jira.opensciencedatacloud.org/browse/TT-202

TT-202: added new rna exp workflow types

---

gdcdictionary/examples/valid/project.json
gdcdictionary/schemas/project.yaml

https://jira.opensciencedatacloud.org/browse/TT-252

TT-252: new project prop is_legacy

---

gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/TT-257

TT-275: new sample types for HCMI

---

gdcdictionary/schemas/project.yaml

https://jira.opensciencedatacloud.org/browse/TT-266

TT-266: new project state processed

---

gdcdictionary/schemas/exposure.yaml

https://jira.opensciencedatacloud.org/browse/TT-214
Please review

TT-214: Deleted 6 from tobacco_smoking_status

---

gdcdictionary/schemas/somatic_mutation_calling_workflow.yaml

https://jira.opensciencedatacloud.org/browse/TT-206
Please Review

TT-206: Added new workflow_type

---

gdcdictionary/schemas/gene_expression.yaml

https://jira.opensciencedatacloud.org/browse/TT-204

TT-204: new gene expression data format and type enums

---

gdcdictionary/examples/valid/demographic.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/demographic.yaml

https://jira.opensciencedatacloud.org/browse/TT-181

TT-181: added age_at_index to demo

---

gdcdictionary/schemas/somatic_aggregation_workflow.yaml

https://jira.opensciencedatacloud.org/browse/TT-215

TT-215: new GENIE and Pindel somatic agg workflow types

---

gdcdictionary/schemas/alignment_workflow.yaml

fix(alignmentw): removed unnecessary quotes
https://jira.opensciencedatacloud.org/browse/TT-201

TT-201: added new alignment workflow types

---

gdcdictionary/schemas/alignment_workflow.yaml

https://jira.opensciencedatacloud.org/browse/TT-174

TT-174: alignment workflow links many to many

---

gdcdictionary/schemas/aggregated_somatic_mutation.yaml

https://jira.opensciencedatacloud.org/browse/TT-173

TT-173: agg somatic mutation many to one with project

---

gdcdictionary/schemas/masked_somatic_mutations.yaml

https://jira.opensciencedatacloud.org/browse/TT-172

TT-172: masked somatic mutation many to one with project

---

gdcdictionary/schemas/diagnosis.yaml

fix(diagnosis): removed trailing whitespace
https://jira.opensciencedatacloud.org/browse/TT-121

TT-121: diagnosis year/age num to int

---

gdcdictionary/schemas/submitted_genomic_profile.yaml

https://jira.opensciencedatacloud.org/browse/TT-115

TT-115: added MAF to s.g.p data formats

---

gdcdictionary/examples/valid/treatment.json
gdcdictionary/schemas/treatment.yaml

https://jira.opensciencedatacloud.org/browse/TT-213

TT-213: days_to_treatment num to int

---

gdcdictionary/schemas/rna_expression_workflow.yaml

fix(rnaworkflow): removed trailing whitespace
https://jira.opensciencedatacloud.org/browse/TT-171

TT-171: rna workflow many-to-one

---

gdcdictionary/schemas/follow_up.yaml

https://jira.opensciencedatacloud.org/browse/TT-290

TT-290: remove None from comorbidity enum

---

gdcdictionary/examples/valid/diagnosis.json
gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/TT-192

TT-192: diagnosis.site_of_resection_or_biopsy string to enum

---

gdcdictionary/schemas/case.yaml

feat(TT-189): removed None from primary_site

TT-189: case.primary_site string to enum

---

gdcdictionary/examples/valid/case.json
gdcdictionary/schemas/case.yaml

https://jira.opensciencedatacloud.org/browse/TT-188

TT-188: case.disease_type string to enum

---

gdcdictionary/examples/valid/treatment.json
gdcdictionary/schemas/treatment.yaml

https://jira.opensciencedatacloud.org/browse/TT-187

TT-187: treatment.treatment_intent_type string to enum

---

gdcdictionary/examples/valid/diagnosis.json
gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/TT-185

TT-185: enumerate diagnosis.primary_diagnosis

---

gdcdictionary/schemas/exposure.yaml

https://jira.opensciencedatacloud.org/browse/TT-247

TT-247: exposure.alcohol_history string to enum

---

gdcdictionary/examples/valid/diagnosis.json
gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/TT-193

TT-193: diagnosis.tumor_grade string to enum

---

gdcdictionary/examples/valid/exposure.json
gdcdictionary/schemas/exposure.yaml

https://jira.opensciencedatacloud.org/browse/TT-191

TT-191: exposure.alcohol_intensity string to enum

---

gdcdictionary/examples/valid/family_history.json
gdcdictionary/schemas/family_history.yaml

feat(TT-67): added Unrelated to relationship_type
fix(TT-67): removed Dont Know relationship_type enum
https://jira.opensciencedatacloud.org/browse/TT-67

TT-67: enumerate relationship primary diag and type

---

gdcdictionary/schemas/treatment.yaml

https://jira.opensciencedatacloud.org/browse/TT-226

TT-226: added enums to  treatment type from TCGA

---

gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/TT-244

TT-244: added enums to method of diagnosis

---

gdcdictionary/examples/valid/diagnosis.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/TT-265

TT-265: add vascular invasion type to diagnosis

---

gdcdictionary/schemas/follow_up.yaml

https://jira.opensciencedatacloud.org/browse/TT-225

TT-225: added enums to followup comorbidity

---

gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/TT-245

TT-245: Not Reported to perineural_invasion_present

---

gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/TT-242

TT-242: add enums to diagnosis laterality

---

gdcdictionary/schemas/demographic.yaml

https://jira.opensciencedatacloud.org/browse/TT-264
Pls Review

TT-264: Added new items to enum cause_of_death

---

gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/TT-274
Pls Review

TT-274: Added new items to enum method_of_sample_procurement

---

gdcdictionary/schemas/treatment.yaml

https://jira.opensciencedatacloud.org/browse/TT-221
Pls Review

TT-221: Added new items to enum treatment_anatomic_site

---

gdcdictionary/schemas/treatment.yaml

https://jira.opensciencedatacloud.org/browse/TT-251
Pls Review

TT-251: Added new items to enum treatment_outcome

---

gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/TT-246
Pls Review

TT-246: Added new items to enum residual_disease

---

gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/TT-241
Pls Review

TT-241: Added new item to enum figo_stage

---

gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/TT-243
Pls Review

TT-243: Added new item to enum lymphatic_invasion_present

---

gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/TT-240
Pls Review

TT-240: Added new items to enum ann_arbor_pathologic_stage

---

gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/TT-222
Pls Review

TT-222: Added new items to enum ann_arbor_clinical_stage

---

gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/TT-239
Please Review

TT-239: Added new items to enum ajcc_pathologic_stage

---

gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/TT-238
Pls Review

TT-238 : Added new items to enum ajcc_clinical_stage

---

gdcdictionary/examples/valid/diagnosis.json
gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/TT-190

TT-190: enumerate diagnosis.tissue_or_organ_of_origin

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/TT-253

TT-253: update bmi term

---

gdcdictionary/schemas/analyte.yaml

Per Bill we don't want portions to be required but want either a link to portions or samples.

TT-259: analyte link requirements changed

---

gdcdictionary/schemas/demographic.yaml

https://jira.opensciencedatacloud.org/browse/TT-320
@madopal

TT-320: unknown to ethnicity enum for xml

---

gdcdictionary/schemas/demographic.yaml

https://jira.opensciencedatacloud.org/browse/TT-321

TT-321: unknown to race enum for xml

---

gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/TT-322

TT-322: vital status not allowed to collect enum for xml

---

gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/exposure.yaml

https://jira.opensciencedatacloud.org/browse/TT-383
Pls review.

feat(TT-383) : added new field to exposure node

---

gdcdictionary/examples/valid/read_group.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/read_group.yaml

https://jira.opensciencedatacloud.org/browse/TT-415
Add field read_groups.target_capture_kit with necessary enums, changes to _terms.yaml, and modified example JSON.

TT-415: Added new property read_groups.target_capture_kit

---

gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/TT-529

TT-529: biospecimen_anatomic_site enums for HCMI

---

gdcdictionary/schemas/annotation.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1331
Added new node links and reordered in alphabetic order, Pls Review.

feat(DAT-1331): Added links to all the required nodes

---

gdcdictionary/examples/valid/copy_number_variation_workflow.json
gdcdictionary/schemas/copy_number_variation_workflow.yaml

https://jira.opensciencedatacloud.org/browse/TT-440
Pls Review.

feat(TT-440): Added new node copy_number_variation_workflow

---

gdcdictionary/examples/valid/copy_number_estimate.json
gdcdictionary/schemas/copy_number_estimate.yaml

https://jira.opensciencedatacloud.org/browse/TT-439
Pls Review.

feat(TT-439): Added new node copy_number_estimate

---

gdcdictionary/schemas/diagnosis.yaml
gdcdictionary/schemas/exposure.yaml
gdcdictionary/schemas/read_group.yaml
gdcdictionary/schemas/treatment.yaml

https://jira.opensciencedatacloud.org/browse/TT-421

TT-421: added deprecated properties

---

gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/TT-509
Added "Next Generation Cancer Model" to enum values for samples.sample_type

TT-509: Add new enum value to samples.sample_type

---

gdcdictionary/schemas/treatment.yaml

https://jira.opensciencedatacloud.org/browse/TT-523
Pls Review.

feat(TT-523): removed values from treatment_type

---

gdcdictionary/schemas/follow_up.yaml

https://jira.opensciencedatacloud.org/browse/TT-500
Pls Review

feat(TT-500): Added new values to comorbidity

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/TT-524

TT-524: updated Ann Arbor terms

---

gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/TT-527

TT-527: new sample composition enum

---

gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/TT-528

TT-528: new sample procurement method enum

---

gdcdictionary/schemas/alignment_workflow.yaml

https://jira.opensciencedatacloud.org/browse/TT-479

TT-479: new alignment workflow type

---

gdcdictionary/schemas/treatment.yaml

https://jira.opensciencedatacloud.org/browse/TT-498

TT-498: new treatment_outcome enums

---

gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/TT-510
Removed seven enum values from samples.sample_type.

TT-510: Remove samples.sample_type enum values

---

gdcdictionary/schemas/read_group.yaml

https://jira.opensciencedatacloud.org/browse/TT-505
Pls Review.

feat(TT-505): removed value from library_selection

---

gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/aliquot.yaml

https://jira.opensciencedatacloud.org/browse/TT-416
Added new no_matched_normal properties & new lines between properties, Pls Review.

feat(TT-416): Added new no_matched_normal properties

---

gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/TT-495
Pls Review.

feat(TT-495): Added new enum values & reorder vascular_invasion_present

---

gdcdictionary/schemas/treatment.yaml

https://jira.opensciencedatacloud.org/browse/TT-494
Pls Review.

feat(TT-494): Added new enum value to treatment_intent_type

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/TT-492
Pls Review.

feat(TT-492): Added cde value to treatment_anatomic_site

---

gdcdictionary/schemas/project.yaml

https://jira.opensciencedatacloud.org/browse/TT-429
Pls Review.

feat(TT-429):Added new property submission_disabled

---

gdcdictionary/schemas/project.yaml

https://jira.opensciencedatacloud.org/browse/TT-428
Pls Review.

feat(TT-428):Added new property in_review

---

gdcdictionary/schemas/submitted_unaligned_reads.yaml

https://jira.opensciencedatacloud.org/browse/TT-405
Added new values to enum experimental_strategy and new lines between properties, Pls Review.

feat(TT-405): Added new values to enum experimental_strategy

---

gdcdictionary/schemas/submitted_genomic_profile.yaml

https://jira.opensciencedatacloud.org/browse/TT-
Added new enum values and new lines between properties, also reordered data_format enum values, Pls Review.

feat(TT-461): Added new enum values and new lines between properties

---

gdcdictionary/schemas/genomic_profile_harmonization_workflow.yaml

https://jira.opensciencedatacloud.org/browse/TT-
Added new enum value to workflow_type and new line between properties, Pls Review.

feat(TT-466): added new enum value to workflow_type

---

gdcdictionary/schemas/simple_somatic_mutation.yaml

https://jira.opensciencedatacloud.org/browse/TT-467
Added new enum values, for data_category- modified enum definition and new lines in between properties Pls Review.

feat(TT-467): added new enum values

---

gdcdictionary/schemas/read_group.yaml

https://jira.opensciencedatacloud.org/browse/TT-472
Pls Review.

feat(TT-472): added library_selection to required list

---

gdcdictionary/schemas/read_group.yaml

https://jira.opensciencedatacloud.org/browse/TT-484
Pls Review.

feat(TT-484): removed duplicate instance of validators on read_group

---

gdcdictionary/schemas/analyte.yaml

https://jira.opensciencedatacloud.org/browse/TT-486
removed duplicate instance of project and moved to program under category to follow other node definitions, Pls Review.

feat(TT-486): removed duplicate instance of project

---

gdcdictionary/schemas/project.yaml

https://jira.opensciencedatacloud.org/browse/TT-483
Pls Review.

feat(TT-483): removed duplicate instance of intended_release_date

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/TT-488
Pls Review

feat(TT-488): updated descriptions for primary_site and disease_type

---

gdcdictionary/schemas/demographic.yaml

https://jira.opensciencedatacloud.org/browse/TT-489
Pls Review.

feat(TT-489): changed type for year_of_birth

---

gdcdictionary/schemas/demographic.yaml

https://jira.opensciencedatacloud.org/browse/TT-490
Pls Review.

feat(TT-490): chaged the type for days_to_death

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/TT-463
Updated descriptions for read_group fields: flow_cell_barcode, multiplex_barcode, lane_number

TT-463: Update read_group field descriptions

---

gdcdictionary/schemas/submitted_aligned_reads.yaml

https://jira.opensciencedatacloud.org/browse/TT-404
submitted_aligned_reads.experimental_strategy
Removed: "Total RNA-Seq", "Validation"
Added: "Targeted Sequencing",  "Bisulfite-Seq", "ChIP-Seq", "ATAC-Seq"

TT-404: +/- enum values from submitted_aligned_reads.experimental_strategy

---

gdcdictionary/examples/valid/demographic.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/demographic.yaml

https://jira.opensciencedatacloud.org/browse/TT-379
Added two new fields, updated _terms, updated valid example JSON

TT-379: Add two new fields to demographics

---

gdcdictionary/schemas/alignment_workflow.yaml

https://jira.opensciencedatacloud.org/browse/TT-426
Added "BWA with Mark Duplicates and BQSR" enum value to alignment_workflow.workflow_type

feat(TT-426): add enum to alignment_workflow.workflow_type

---

gdcdictionary/schemas/follow_up.yaml

https://jira.opensciencedatacloud.org/browse/TT-401
Pls review.

feat(TT-401) : added optional link between follow_up and diagnosis

---

gdcdictionary/schemas/read_group.yaml

https://jira.opensciencedatacloud.org/browse/TT-449
Removed Poly-T_Enrichment from library_selection on node read_group

feat/TT-449: removed one value from read_group.library_selection

---

gdcdictionary/schemas/read_group.yaml

https://jira.opensciencedatacloud.org/browse/TT-402
Pls review.

feat(TT-402): Added new value to library_strand

---

gdcdictionary/examples/valid/molecular_test.json
gdcdictionary/schemas/_definitions.yaml
gdcdictionary/schemas/molecular_test.yaml

add ubiquitous_properties definition
https://jira.opensciencedatacloud.org/browse/DAT-1247
@madopal

DAT-1247: new molecular_test node

---

gdcdictionary/schemas/masked_somatic_mutations.yaml

https://jira.opensciencedatacloud.org/browse/TT-530

TT-530: msm edge to gphw

---

gdcdictionary/schemas/demographic.yaml
gdcdictionary/schemas/diagnosis.yaml
gdcdictionary/schemas/exposure.yaml

https://jira.opensciencedatacloud.org/browse/TT-534

TT-534: changed preferred props

---

gdcdictionary/schemas/masked_somatic_mutations.yaml

https://jira.opensciencedatacloud.org/browse/TT-532

TT-532: removed Validation from exp strat

---

gdcdictionary/schemas/biospecimen_supplement.yaml

https://jira.opensciencedatacloud.org/browse/TT-397
Pls review.

feat(TT-397):remove enum values from data_format

---

gdcdictionary/examples/valid/alignment_workflow.json
gdcdictionary/schemas/alignment_workflow.yaml

feat(TT-422): updated example for nonexclusivity
https://jira.opensciencedatacloud.org/browse/TT-422

TT-422: alignment link no longer exclusive

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/TT-412

TT-412: update prior malignancy description

---

gdcdictionary/examples/valid/read_group.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/read_group.yaml

https://jira.opensciencedatacloud.org/browse/TT-411

TT-411: new read pair number prop

---

gdcdictionary/schemas/_definitions.yaml
gdcdictionary/schemas/file.yaml

https://jira.opensciencedatacloud.org/browse/TT-403

TT-403: file_size type integer

---

gdcdictionary/examples/valid/treatment.json
gdcdictionary/schemas/treatment.yaml

https://jira.opensciencedatacloud.org/browse/TT-417

TT-417: remove treatment.days_to_treatment

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/TT-365

TT-365: updated descriptions for HCMI

---

gdcdictionary/schemas/_terms.yaml

Changed descriptions to match spreadsheet.
https://jira.opensciencedatacloud.org/browse/TT-384

TT-384: updated descriptions for HCMI

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/TT-400

TT-400: md5sum description lower case

---

gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1362

DAT-1362: new BCR sample type id

---

gdcdictionary/examples/valid/diagnosis.json
gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1364

DAT-1364: fix diagnosis enums

---

gdcdictionary/schemas/sample.yaml

- Restore pathology_report to sample, it somehow got munged

fix(sample): Restore pathology_report to sample

---

gdcdictionary/schemas/clinical.yaml
gdcdictionary/schemas/diagnosis.yaml
gdcdictionary/schemas/exposure.yaml
gdcdictionary/schemas/family_history.yaml

https://jira.opensciencedatacloud.org/browse/TT-609

TT-609: required submitter_id on all nodes

---

gdcdictionary/schemas/rna_expression_workflow.yaml

https://jira.opensciencedatacloud.org/browse/TT-660

TT-660: new rna expression workflow type

---

gdcdictionary/schemas/somatic_mutation_calling_workflow.yaml

https://jira.opensciencedatacloud.org/browse/TT-661

TT-661: new mutation calling workflow type

---

gdcdictionary/schemas/somatic_annotation_workflow.yaml

https://jira.opensciencedatacloud.org/browse/TT-662

TT-662: new annoation workflow type

---

gdcdictionary/schemas/gene_expression.yaml

https://jira.opensciencedatacloud.org/browse/TT-663

TT-663: added splice junction data type

---

gdcdictionary/schemas/annotated_somatic_mutation.yaml

https://jira.opensciencedatacloud.org/browse/TT-664

TT-664: new MAF data format

---

gdcdictionary/schemas/annotated_somatic_mutation.yaml

https://jira.opensciencedatacloud.org/browse/TT-665

TT-665: new enum for data type

---

gdcdictionary/schemas/alignment_workflow.yaml

https://jira.opensciencedatacloud.org/browse/TT-659

TT-659: new alignment workflow type

---

gdcdictionary/examples/valid/read_group.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/read_group.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1533

DAT-1533: new days_to_seq prop

---

gdcdictionary/schemas/read_group.yaml

https://jira.opensciencedatacloud.org/browse/TT-667

TT-667: new capture kit enums

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/TT-683

TT-683: updated days_to_birth/death descriptions

---

gdcdictionary/schemas/case.yaml

https://jira.opensciencedatacloud.org/browse/TT-678

TT-678: new enum for index date

---

gdcdictionary/schemas/read_group_qc.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1523

DAT-1523: unrequire rg qc props

---

gdcdictionary/schemas/_definitions.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1525

DAT-1525: unknown/not reported to qc state props

---

gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1560

DAT-1560: removed vascular invasion present enums

---

gdcdictionary/examples/valid/diagnosis.json
gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/TT-686

TT-686: removed ldh_level_at_diagnosis property

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1548

DAT-1548: updated treatment_or_therapy description

---

gdcdictionary/schemas/molecular_test.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1553

DAT-1553: Not Applicable added to gene symbol

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1549

DAT-1549: updated therapeutic agents description

---

gdcdictionary/schemas/submitted_genomic_profile.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1559

DAT-1559: add experimental strategies to submitted genomic profile

---

gdcdictionary/schemas/annotated_somatic_mutation.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1554

DAT-1554: updated experimental_strategy values

---

gdcdictionary/schemas/simple_germline_variation.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1556

DAT-1556: updated simple germline experimental strat

---

gdcdictionary/schemas/simple_somatic_mutation.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1558

DAT-1558: updated simple somatic mutation exp strats

---

gdcdictionary/schemas/aliquot.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1519

DAT-1519: aliquot exclusive link with sample/aliquot

---

gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1579

DAT-1579: new vascular envasion type enums

---

gdcdictionary/schemas/treatment.yaml

https://jira.opensciencedatacloud.org/browse/TT-672

TT-672: update treatment type enum

---

gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1567

DAT-1567: new ajcc clinical stage enum

---

gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1571

DAT-1571: new method of diagnosis enums

---

gdcdictionary/schemas/follow_up.yaml

https://jira.opensciencedatacloud.org/browse/TT-674

TT-674: new risk factor enums

---

gdcdictionary/schemas/metaschema.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1347

DAT-1347: update metaschema with keyword descriptions

---

gdcdictionary/schemas/treatment.yaml

https://jira.opensciencedatacloud.org/browse/TT-680

TT-680: update treatment_outcome enum

---

gdcdictionary/schemas/follow_up.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1581

DAT-1581: update progression or recurrence type enum

---

gdcdictionary/schemas/follow_up.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1584

DAT-1584: update disease response enum

---

gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/TT-673

TT-673: updated metastasis diagnosis site enum

---

gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1634

DAT-1634: fixed typo in ubiquitous props ref

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1590

DAT-1590: udpated case node terms

---

gdcdictionary/schemas/submitted_unaligned_reads.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1651

DAT-1651: add NA to read_pair_number enum

---

gdcdictionary/schemas/submitted_unaligned_reads.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1648

DAT-1648: required read_pair_number

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1592

DAT-1592: updated diagnosis terms

---

gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/family_history.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1635

DAT-1635: updated family_history terms

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/TT-254

TT-254: updated family_history terms

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1594

DAT-1594: updated followup terms

---

gdcdictionary/schemas/_terms.yaml

fix(DAT-1596): remove trailing whitespace
https://jira.opensciencedatacloud.org/browse/DAT-1596

DAT-1596: update treatment terms

---

gdcdictionary/schemas/molecular_test.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1665

DAT-1665: new test result enums

---

gdcdictionary/examples/valid/molecular_test.json
gdcdictionary/schemas/molecular_test.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1639

DAT-1639: deleted blood test

---

gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/molecular_test.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1644

DAT-1644: added lab test and biospecimen type

---

gdcdictionary/schemas/molecular_test.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1663

DAT-1663: new molecular analysis method enums

---

gdcdictionary/schemas/molecular_test.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1662

DAT-1662: new antigen enums

---

gdcdictionary/examples/valid/treatment.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/treatment.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1647

DAT-1647: add initial_disease_status

---

gdcdictionary/schemas/treatment.yaml

https://jira.opensciencedatacloud.org/browse/TT-681

TT-681: deleted treatment intent type enums

---

gdcdictionary/schemas/molecular_test.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1664

DAT-1664: new variant_type enums

---

gdcdictionary/schemas/case.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1669

DAT-1669: added first treatment index date

---

gdcdictionary/schemas/case.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1461

DAT-1461: new index date enum

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1591

DAT-1591: update demographic node terms

---

gdcdictionary/schemas/follow_up.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1766

DAT-1766: new comorbidity enums

---

gdcdictionary/schemas/treatment.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1889

DAT-1889: treatment age min/max

---

gdcdictionary/schemas/read_group.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1814

DAT-1814: added ATAC seq to library strat

---

gdcdictionary/examples/valid/diagnosis.json
gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1885

DAT-1885: diagnosis days min/max

---

gdcdictionary/schemas/diagnosis.yaml

feat(DAT-1879): new primary diagnosis enums

DAT-1879: new primary diag enums

---

gdcdictionary/examples/valid/portion.json
gdcdictionary/schemas/portion.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1870

DAT-1870: portion number now int

---

gdcdictionary/schemas/follow_up.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1841

DAT-1841: new risk factor enums

---

gdcdictionary/examples/valid/molecular_test.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/molecular_test.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1847

DAT-1847: added intron prop

---

gdcdictionary/examples/valid/molecular_test.json
gdcdictionary/schemas/molecular_test.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1874

DAT-1874: added locus regex

---

gdcdictionary/examples/valid/molecular_test.json
gdcdictionary/schemas/molecular_test.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1916

DAT-1916: transcript regex added

---

gdcdictionary/schemas/follow_up.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1684

DAT-1684: new ecog perform status enums

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1763

DAT-1763: update instrument model description

---

gdcdictionary/schemas/read_group.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1799

DAT-1799: new target capture kit enum

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1801

DAT-1801: update analyte volume description

---

gdcdictionary/examples/valid/diagnosis.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1832

DAT-1832: tumor focality added

---

gdcdictionary/examples/valid/diagnosis.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1834

DAT-1834: lymph nodes tested added

---

gdcdictionary/examples/valid/exposure.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/exposure.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1836

DAT-1836: asbestos exposure added

---

gdcdictionary/examples/valid/exposure.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/exposure.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1837

DAT-1837: radon exposure added

---

gdcdictionary/schemas/follow_up.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1840

DAT-1840: new disease response enums

---

gdcdictionary/examples/valid/follow_up.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/follow_up.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1845

DAT-1845: hepatitis sus viral reponse prop added

---

gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1849

DAT-1849: new procurment method enums

---

gdcdictionary/examples/valid/aligned_reads.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/aligned_reads.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1749

DAT-1749: added contamination props

---

gdcdictionary/examples/valid/family_history.json
gdcdictionary/schemas/family_history.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1887

DAT-1887: relationship age at diag min/max added

---

gdcdictionary/schemas/case.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1888

DAT-1888: days to lost to followup min/max

---

gdcdictionary/examples/valid/sample.json
gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1893

DAT-1893: pathology report uuid regex

---

gdcdictionary/examples/valid/read_group.json
gdcdictionary/schemas/read_group.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1895

DAT-1895: adapter sequence regex

---

gdcdictionary/examples/valid/read_group.json
gdcdictionary/schemas/read_group.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1897

DAT-1897: multiplex barcode regex

---

gdcdictionary/examples/valid/follow_up.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/follow_up.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1843

DAT-1843: add risk factor treatment prop

---

gdcdictionary/examples/valid/treatment.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/treatment.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1850

DAT-1850: added treatment effect prop

---

gdcdictionary/schemas/case.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1772

DAT-1772: removed unknown primary site enum

---

gdcdictionary/schemas/follow_up.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1884

DAT-1884: min max on days_to

---

gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1883

DAT-1883: days to min/max values

---

gdcdictionary/schemas/family_history.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1765

DAT-1765: new rel primary diagnosis enums

---

gdcdictionary/examples/valid/sample.json
gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1861

DAT-1861: intermediate dimension string to number

---

gdcdictionary/examples/valid/demographic.json
gdcdictionary/schemas/demographic.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1886

DAT-1886: min max values for age

---

gdcdictionary/examples/valid/sample.json
gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1863

DAT-1863: longest dimension string to number

---

gdcdictionary/examples/valid/sample.json
gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1865

DAT-1865: shortest dimension type number

---

gdcdictionary/examples/valid/sample.json
gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1867

DAT-1867: clamping and freezing string to number

---

gdcdictionary/examples/valid/sample.json
gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1869

DAT-1869: time excision freezing to number

---

gdcdictionary/examples/valid/follow_up.json
gdcdictionary/schemas/follow_up.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1913

DAT-1913: removed reflux_treatment

---

gdcdictionary/examples/valid/molecular_test.json
gdcdictionary/schemas/molecular_test.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1890

DAT-1890: added regex for exon prop

---

gdcdictionary/examples/valid/diagnosis.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1833

DAT-1833: tumor regression grade added

---

gdcdictionary/examples/valid/raw_methylation_array.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/raw_methylation_array.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1854

DAT-1854: raw methylation array init

---

gdcdictionary/schemas/read_group.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1908

DAT-1908: read length can be null

---

gdcdictionary/schemas/read_group.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1909

DAT-1909: is paired end can be null

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1911

DAT-1911: update comorbidity term

---

gdcdictionary/schemas/_terms.yaml

fix(DAT-1912): quotes and whitespace
https://jira.opensciencedatacloud.org/browse/DAT-1912

DAT-1912: cde for days to comorbidity

---

gdcdictionary/examples/valid/follow_up.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/follow_up.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1684
https://jira.opensciencedatacloud.org/browse/DAT-1766
https://jira.opensciencedatacloud.org/browse/DAT-1840
https://jira.opensciencedatacloud.org/browse/DAT-1841
https://jira.opensciencedatacloud.org/browse/DAT-1843
https://jira.opensciencedatacloud.org/browse/DAT-1845
https://jira.opensciencedatacloud.org/browse/DAT-1884
https://jira.opensciencedatacloud.org/browse/DAT-1911
https://jira.opensciencedatacloud.org/browse/DAT-1912
https://jira.opensciencedatacloud.org/browse/DAT-1913

Marvin follow up node changes

---

gdcdictionary/examples/valid/raw_methylation_array.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/raw_methylation_array.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1854

Marvin new raw methylation array node

---

gdcdictionary/examples/valid/molecular_test.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/molecular_test.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1847
https://jira.opensciencedatacloud.org/browse/DAT-1874
https://jira.opensciencedatacloud.org/browse/DAT-1890
https://jira.opensciencedatacloud.org/browse/DAT-1916

Marvin molecular test node changes

---

gdcdictionary/examples/valid/sample.json
gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1849
https://jira.opensciencedatacloud.org/browse/DAT-1861
https://jira.opensciencedatacloud.org/browse/DAT-1863
https://jira.opensciencedatacloud.org/browse/DAT-1865
https://jira.opensciencedatacloud.org/browse/DAT-1867
https://jira.opensciencedatacloud.org/browse/DAT-1869
https://jira.opensciencedatacloud.org/browse/DAT-1883
https://jira.opensciencedatacloud.org/browse/DAT-1893

Marvin sample node changes

---

gdcdictionary/examples/valid/demographic.json
gdcdictionary/schemas/demographic.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1886

Marvin demographic node changes

---

gdcdictionary/examples/valid/family_history.json
gdcdictionary/schemas/family_history.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1887
https://jira.opensciencedatacloud.org/browse/DAT-1765

Marvin family history node changes

---

gdcdictionary/schemas/case.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1888
https://jira.opensciencedatacloud.org/browse/DAT-1772

Marvin case node changes

---

gdcdictionary/examples/valid/aligned_reads.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/aligned_reads.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1749

Marvin aligned reads node changes

---

gdcdictionary/examples/valid/exposure.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/exposure.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1836
https://jira.opensciencedatacloud.org/browse/DAT-1837

Marvin exposure node changes

---

gdcdictionary/examples/valid/portion.json
gdcdictionary/schemas/portion.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1870

Marvin portion node changes

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1859

DAT-1859: change analyte volume description units

---

gdcdictionary/examples/valid/portion.json
gdcdictionary/schemas/portion.yaml

This reverts commit ca909baaa056ab287c14995c78d0aabd3a5ed062.

Revert "feat(DAT-1870): poriton number now int (#544) (#565)"

---

gdcdictionary/schemas/diagnosis.yaml

- Use type method for days_to_death instead of oneOf

fix(diagnosis): Use type method for days_to_death

---

gdcdictionary/schemas/read_group.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1895

DAT-1895: revert adapter seq regex

---

gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2017

DAT-2017: sample types for BEATAML

---

gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2116

DAT-2116: added new sample types and ids

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/TT-936

TT-936: updated percent tumor cell description

---

gdcdictionary/schemas/slide_image.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2125

DAT-2125: fix magnification description typo

---

gdcdictionary/examples/valid/follow_up.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/follow_up.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2135

DAT-2135: days to progresion free added

---

gdcdictionary/schemas/somatic_aggregation_workflow.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2080

DAT-2080: new workflow type

---

gdcdictionary/examples/valid/diagnosis.json
gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/TT-939

TT-939: removed days to birth/death

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2126

DAT-2126: updated selcted normal descriptions

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1928

DAT-1928: updated primary site description

---

gdcdictionary/schemas/exposure.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2062

DAT-2062: cigarettes per day not deprecated

---

gdcdictionary/schemas/molecular_test.yaml

https://jira.opensciencedatacloud.org/browse/TT-918

TT-918: new test_result enums

---

gdcdictionary/examples/valid/molecular_test.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/molecular_test.yaml

https://jira.opensciencedatacloud.org/browse/TT-919

TT-919: added second exon prop

---

gdcdictionary/schemas/case.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2133

DAT-2133: unknown enum for lost to followup

---

gdcdictionary/examples/valid/annotation.json
gdcdictionary/schemas/annotation.yaml

https://jira.opensciencedatacloud.org/browse/TT-930

TT-930: made annotaiton status an enum

---

gdcdictionary/schemas/read_group.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2013

DAT-2013: new target capture kit

---

gdcdictionary/schemas/read_group.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2002

DAT-2002: new target capture kit

---

gdcdictionary/schemas/somatic_mutation_index.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1986

DAT-1986: somatic muation index not submittable

---

gdcdictionary/schemas/aligned_reads_index.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1985

DAT-1985: aligned read index not submittable

---

gdcdictionary/schemas/read_group.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1827

DAT-1827: new capture kit

---

gdcdictionary/examples/valid/molecular_test.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/molecular_test.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1991

DAT-1991: removed genomic coords

---

gdcdictionary/schemas/somatic_aggregation_workflow.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2112

DAT-2112: oobleck somatic aggregation workflow node

---

gdcdictionary/examples/valid/methylation_array_harmonization_workflow.json
gdcdictionary/schemas/methylation_array_harmonization_workflow.yaml
gdcdictionary/schemas/methylation_beta_value.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2025

DAT-2025: added methylation nodes

---

gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2114

DAT-2114: oobleck sample node

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2106

DAT-2106: oobleck slide node

---

gdcdictionary/schemas/_terms.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2111

DAT-2111: oobleck aliquot node

---

gdcdictionary/examples/valid/follow_up.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/follow_up.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2134

DAT-2134: oobleck follow up node

---

gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/case.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2119

DAT-2119: oobleck case node

---

gdcdictionary/examples/valid/molecular_test.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/molecular_test.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2110

DAT-2110: oobleck molecular test node

---

gdcdictionary/examples/valid/annotation.json
gdcdictionary/schemas/annotation.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2107

DAT-2107: oobleck annotation node

---

gdcdictionary/schemas/read_group.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2115

DAT-2115: oobleck read group node

---

gdcdictionary/schemas/somatic_mutation_index.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2117

DAT-2117: oobleck somatic mutation index node

---

gdcdictionary/schemas/aligned_reads_index.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2118

DAT-2118: oobleck aligned reads index node

---

gdcdictionary/schemas/demographic.yaml
gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2157

DAT-2157: changed vital status requirment location

---

gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2158

DAT-2158: diagnosis vital status deprecated

---

gdcdictionary/examples/valid/methylation_array_harmonization_workflow.json

(cherry picked from commit ba9ce1dac5a064e017e9078affe7af8e5fdef1b2)

fix(test): test data node type methalation_array_harmonization not beta

---

gdcdictionary/examples/valid/molecular_test.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/molecular_test.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2366

DAT-2366: added pathgenicity mt prop

---

gdcdictionary/schemas/aggregated_somatic_mutation.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2311

DAT-2311: update aggsm description

---

gdcdictionary/schemas/annotated_somatic_mutation.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2311

DAT-2311: udpated asm description

---

gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2427

DAT-2427: removed morphology deprecated enum

---

gdcdictionary/schemas/masked_somatic_mutation.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2311

DAT-2311: updated node description

---

gdcdictionary/schemas/annotation.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2238

DAT-2238: enumerate classifcation

---

gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2397

DAT-2397: deprecate tumor stage

---

gdcdictionary/examples/valid/family_history.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/family_history.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2365

DAT-2365: relatives with cancer count

---

gdcdictionary/examples/valid/diagnosis.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2352

DAT-2352: added mitotic count

---

gdcdictionary/examples/valid/diagnosis.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2345

DAT-2345: added brewslow thickness

---

gdcdictionary/schemas/molecular_test.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2374

DAT-2374: new test result enums

---

gdcdictionary/schemas/publication.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2259

DAT-2259: publication downloadable

---

gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2370

DAT-2370: new metastatic site enum

---

gdcdictionary/schemas/molecular_test.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2372

DAT-2372: new antigen enum

---

gdcdictionary/schemas/archive.yaml

fhttps://jira.opensciencedatacloud.org/browse/DAT-2259

DAT-2259: archive downloadable

---

gdcdictionary/examples/valid/demographic.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/demographic.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2341

DAT-2341: cause of death source added

---

gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2376

DAT-2376: new procurement methods

---

gdcdictionary/schemas/filtered_copy_number_segment.yaml

fhttps://jira.opensciencedatacloud.org/browse/DAT-2259

DAT-2259: fcns downloadable

---

gdcdictionary/examples/valid/diagnosis.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2353

DAT-2353: regional disease diag prop

---

gdcdictionary/examples/valid/diagnosis.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2350

DAT-2350: extrapelvic property added

---

gdcdictionary/examples/valid/diagnosis.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2361

DAT-2361: new diagnosis prop

---

gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2368

DAT-2368: new ajcc path stage

---

gdcdictionary/schemas/structural_variation.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2336

DAT-2336: new data format for sv

---

gdcdictionary/schemas/read_group.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2338

DAT-2338: new rg instrument model

---

gdcdictionary/examples/valid/demographic.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/demographic.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2342

DAT-2342: occupation prop to demo

---

gdcdictionary/schemas/demographic.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2314

DAT-2314: added enumDef to gender

---

gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1787

DAT-1787: cfDNA additions for sample

---

gdcdictionary/schemas/analyte.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1787

DAT-1787: added cfDNA analyte type

---

gdcdictionary/schemas/case.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2390

DAT-2390: undeprecate Not Applicable disease type

---

gdcdictionary/schemas/read_group.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2411

DAT-2411: null props for instrument model

---

gdcdictionary/examples/valid/diagnosis.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2349

DAT-2349: prognostic index prop

---

gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2247

DAT-2247: fixed ref typo

---

gdcdictionary/schemas/biospecimen_supplement.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2266

DAT-2266: new biospecimen supplement data format

---

gdcdictionary/examples/valid/demographic.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/demographic.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2303

DAT-2303: age is obfuscated prop added

---

gdcdictionary/schemas/copy_number_segment.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2332

DAT-2332: added new data type

---

gdcdictionary/schemas/copy_number_estimate.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2334

DAT-2334: added WXS to experimental strat

---

gdcdictionary/schemas/read_group.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2310

DAT-2310: new target capture kit

---

gdcdictionary/examples/valid/aligned_reads.json
gdcdictionary/schemas/aligned_reads.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2241

DAT-2241: added msi props to ar

---

gdcdictionary/schemas/annotation.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2450

DAT-2450: link to protein expression

---

gdcdictionary/examples/valid/protein_expression.json
gdcdictionary/schemas/protein_expression.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2237

DAT-2237: added protein expression node

---

gdcdictionary/schemas/annotation.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2450

DAT-2450: link to sub genotyping array

---

gdcdictionary/examples/valid/submitted_genotyping_array.json
gdcdictionary/schemas/submitted_genotyping_array.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2327

DAT-2327: new genotyping array node

---

gdcdictionary/examples/valid/somatic_copy_number_workflow.json
gdcdictionary/schemas/somatic_copy_number_workflow.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2330

DAT-2330: add new workflow for ascat

---

gdcdictionary/schemas/annotation.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2450

DAT-2450: link to raw meth array

---

gdcdictionary/schemas/aggregated_somatic_mutation.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2260

DAT-2260: unrequired maf project link

---

gdcdictionary/schemas/structural_variant_calling_workflow.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2335

DAT-2335: new svcw workflow types

---

gdcdictionary/schemas/annotated_somatic_mutation.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2333

DAT-2333: new link to profile harmonization

---

gdcdictionary/schemas/genomic_profile_harmonization_workflow.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2388

DAT-2388: new gphw wf type

---

gdcdictionary/schemas/somatic_mutation_calling_workflow.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2389

DAT-2389: new smcw wf type

---

gdcdictionary/schemas/somatic_annotation_workflow.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2391

DAT-2391: new saw wf type

---

gdcdictionary/schemas/copy_number_segment.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2331

DAT-2331: cns links to scnw

---

gdcdictionary/schemas/follow_up.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2371

DAT-2371: new risk factors in followup

---

gdcdictionary/schemas/copy_number_estimate.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2415

DAT-2415: cne to scnw link

---

gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2418

DAT-2418: new sample type and id

---

gdcdictionary/schemas/annotation.yaml

Reverts NCI-GDC/gdcdictionary#703

Revert "feat(annotations): Annotation node updates for QQ"

---

gdcdictionary/schemas/publication.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2259

feat(pub): update publication for qq

---

gdcdictionary/schemas/archive.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2259

feat(archive): update archive for qq

---

gdcdictionary/schemas/filtered_copy_number_segment.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2259

feat(fcns): update filtered cn seg for qq

---

gdcdictionary/schemas/structural_variation.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2336

feat(sv): update structural variation for qq

---

gdcdictionary/examples/valid/molecular_test.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/molecular_test.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2373
https://jira.opensciencedatacloud.org/browse/DAT-2372
https://jira.opensciencedatacloud.org/browse/DAT-2374
https://jira.opensciencedatacloud.org/browse/DAT-2366

feat(mt): update molecular test for qq

---

gdcdictionary/schemas/case.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2390

feat(case): update case for qq

---

gdcdictionary/schemas/biospecimen_supplement.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2266

feat(bsup): update biospecimen supplement for qq

---

gdcdictionary/examples/valid/demographic.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/demographic.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2341
https://jira.opensciencedatacloud.org/browse/DAT-2342
https://jira.opensciencedatacloud.org/browse/DAT-2303
https://jira.opensciencedatacloud.org/browse/DAT-2314

feat(demo): update demographic for qq

---

gdcdictionary/examples/valid/aligned_reads.json
gdcdictionary/schemas/aligned_reads.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2241

feat(ar): aligned reads changes for qq

---

gdcdictionary/schemas/read_group.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2338
https://jira.opensciencedatacloud.org/browse/DAT-2310
https://jira.opensciencedatacloud.org/browse/DAT-2411

feat(rg): read group changes for qq

---

gdcdictionary/schemas/analyte.yaml

https://jira.opensciencedatacloud.org/browse/DAT-1787

feat(analyte): update analyte for qq

---

gdcdictionary/schemas/_definitions.yaml

[FEAT] API-755: Add Deleted to File States

---

setup.py

-Correcting minor bump to micro bump for release/redfish

chore(redfish): tag

---

setup.py

Reverts NCI-GDC/gdcdictionary#741

Revert "chore(sync): py3 with develop"

---

gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/aligned_reads.yaml
gdcdictionary/schemas/annotation.yaml
gdcdictionary/schemas/archive.yaml
gdcdictionary/schemas/center.yaml
gdcdictionary/schemas/clinical.yaml
gdcdictionary/schemas/data_format.yaml
gdcdictionary/schemas/data_release.yaml
gdcdictionary/schemas/data_subtype.yaml
gdcdictionary/schemas/data_type.yaml
gdcdictionary/schemas/experimental_strategy.yaml
gdcdictionary/schemas/platform.yaml
gdcdictionary/schemas/program.yaml
gdcdictionary/schemas/project.yaml
gdcdictionary/schemas/read_group.yaml
gdcdictionary/schemas/sample.yaml
gdcdictionary/schemas/slide_image.yaml
gdcdictionary/schemas/submitted_genotyping_array.yaml
gdcdictionary/schemas/tag.yaml
gdcdictionary/schemas/tissue_source_site.yaml

Updated the descriptions to have same format across dictionary

DAT-2812: Updated the descriptions to have same format

---

gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/aligned_reads.yaml

the ticket number in the branch name (DAT-2705) was incorrect. Changing the ticket description to reflect the correct ticket number (DAT-2794).

DAT-2794_DAT-2787:changes to aligned reads

---

gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/case.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2746

DAT-2746:changes to case node (updated)

---

gdcdictionary/schemas/structural_variation.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2703

feat/DAT-2703: updated structural variation node

---

gdcdictionary/schemas/somatic_mutation_index.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2704
https://jira.opensciencedatacloud.org/browse/DAT-2807

feat/DAT-2704_DAT-2807: updated links & added enum

---

gdcdictionary/schemas/somatic_copy_number_workflow.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2705

feat/DAT-2705: updated links

---

gdcdictionary/schemas/slide.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2747

feat/DAT-2747:changes to slide node

---

gdcdictionary/schemas/expression_analysis_workflow.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2802

feat/DAT-2802: Added new node yaml

---

gdcdictionary/schemas/secondary_expression_analysis.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2803

feat/DAT-2803: Added new node yaml

---

gdcdictionary/schemas/copy_number_segment.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2706
The ticket number the branch name refers to another ticket which is on same node but closed so ignore it

feat/DAT-2706: updated copy number segment node

---

gdcdictionary/schemas/copy_number_estimate.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2729

feat/DAT-2729: updated copy number estimate node

---

gdcdictionary/schemas/gene_expression.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2794
https://jira.opensciencedatacloud.org/browse/DAT-2804

feat/DAT-2794_ge: updated gene expression node

---

gdcdictionary/schemas/rna_expression_workflow.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2796

feat/DAT-2796: updated rna expression workflow node

---

gdcdictionary/schemas/alignment_workflow.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2795

feat/DAT-2795: updated alignment workflow node

---

gdcdictionary/schemas/submitted_aligned_reads.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2794

feat/DAT-2794_ar: updated submitted aligned reads node

---

gdcdictionary/schemas/submitted_unaligned_reads.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2794
https://jira.opensciencedatacloud.org/browse/DAT-2799

feat/DAT-2799: updated submitted unaligned reads node

---

gdcdictionary/schemas/family_history.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2738

feat/DAT-2738: updated family history node

---

gdcdictionary/schemas/read_group.yaml

feat/read_group: DAT-2755, DAT-2793, DAT-2798, DAT-2800 : updated read_group yaml
https://jira.opensciencedatacloud.org/browse/DAT-2755
https://jira.opensciencedatacloud.org/browse/DAT-2793
https://jira.opensciencedatacloud.org/browse/DAT-2798
https://jira.opensciencedatacloud.org/browse/DAT-2800

feat/read_group: DAT-2755, DAT-2793, DAT-2798, DAT-2800

---

gdcdictionary/schemas/somatic_copy_number_workflow.yaml

@tlicht3 pointed that the reqd property was wrong so fixed it.

updated reqd property on the link

---

gdcdictionary/schemas/expression_analysis_workflow.yaml

target_type: aligned_reads_file is wrong so updated to correct value

updated link target to refer to correct value

---

gdcdictionary/schemas/demographic.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2733

feat/DAT-2733: changes to demographic node

---

gdcdictionary/schemas/slide_image.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2808

feat/DAT-2808: updates to slide_image node

---

gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2735

DAT-2735: changes to diagnosis node

---

gdcdictionary/schemas/exposure.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2737

feat/DAT-2737: changes to exposure

---

gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2742

feat/DAT-2742:changes to the sample node

---

gdcdictionary/schemas/follow_up.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2739

feat/DAT-2739:updates to the follow_up node

---

gdcdictionary/schemas/molecular_test.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2741

feat/DAT-2741:updates to molecular_test node

---

gdcdictionary/examples/valid/treatment.json
gdcdictionary/schemas/treatment.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2745

feat/DAT-2745_DAT-2727:updates to treatment node

---

gdcdictionary/schemas/expression_analysis_workflow.yaml

https://jira.opensciencedatacloud.org/browse/DAT-2802

updated links per updated ticket

---

.secrets.baseline
gdcdictionary/examples/valid/masked_methylation_array.json
gdcdictionary/schemas/masked_methylation_array.yaml
requirements.txt
setup.py

https://jira.opensciencedatacloud.org/browse/DICT-60

feat/masked_methylation_array: initial version

---

gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/sample.yaml

For complete details reference this ticket: https://jira.opensciencedatacloud.org/browse/DICT-58

DICT-58: Updates to the SAMPLE node - YERTLE

---

gdcdictionary/schemas/treatment.yaml

For a complete list of changes refer to this ticket: https://jira.opensciencedatacloud.org/browse/DICT-57

DICT-57: Updates to the TREATMENT node - YERTLE

---

gdcdictionary/schemas/molecular_test.yaml

To see all of the changes reference this JIRA ticket: https://jira.opensciencedatacloud.org/browse/DICT-56

DICT-56: Updates to the MOLECULAR TEST Node - YERTLE

---

gdcdictionary/schemas/aligned_reads.yaml

For complete details, reference this ticket: https://jira.opensciencedatacloud.org/browse/DICT-73

DICT-73: Updates to ALIGNED READS node - YERTLE

---

gdcdictionary/examples/valid/exposure.json
gdcdictionary/schemas/exposure.yaml

For complete details for these changes see this ticket: https://jira.opensciencedatacloud.org/browse/DICT-63

DICT-63: Updates to the EXPOSURE node - YERTLE

---

gdcdictionary/schemas/analyte.yaml

For complete details, see this ticket: https://jira.opensciencedatacloud.org/browse/DICT-66

DICT-66: Updates to the ANALYTE node - YERTLE

---

gdcdictionary/schemas/submitted_aligned_reads.yaml

For complete details, reference this ticket: https://jira.opensciencedatacloud.org/browse/DICT-71

DICT-71: Updates to SUBMITTED ALIGNED READS node - YERTLE

---

gdcdictionary/schemas/submitted_unaligned_reads.yaml

For complete details, reference this ticket: https://jira.opensciencedatacloud.org/browse/DICT-72

DICT-72: Updates to SUBMITTED UNALIGNED READS node - YERTLE

---

gdcdictionary/schemas/rna_expression_workflow.yaml

For complete details, reference this ticket: https://jira.opensciencedatacloud.org/browse/DICT-53

DICT-53: Updates to the RNA EXPRESSION WORKFLOW node - YERTLE

---

gdcdictionary/schemas/center.yaml

For complete details, reference this ticket: https://jira.opensciencedatacloud.org/browse/DICT-69

DICT-69: Updates to CENTER node - YERTLE

---

gdcdictionary/examples/valid/case.json
gdcdictionary/schemas/case.yaml

For complete details for the changes, see this ticket: https://jira.opensciencedatacloud.org/browse/DICT-62

DICT-62: Updates to the CASE node - YERTLE

---

gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/pathology_detail.yaml

For complete details for this PR, reference this ticket: https://jira.opensciencedatacloud.org/browse/DICT-61

DICT-61: Updates to the PATHOLOGY DETAILS node

---

gdcdictionary/schemas/follow_up.yaml

Updates for this ticket can be found here: https://jira.opensciencedatacloud.org/browse/DICT-55

DICT-55: Updates to the FOLLOW-UP file - YERTLE

---

gdcdictionary/schemas/read_group.yaml

For complete details, reference this ticket: https://jira.opensciencedatacloud.org/browse/DICT-75

DICT-75: Updates to READ GROUP node - YERTLE

---

gdcdictionary/schemas/raw_methylation_array.yaml

For complete details, see this ticket: https://jira.opensciencedatacloud.org/browse/DICT-70

DICT-70: Updates to the RAW METHYLATION ARRAY node - YERTLE

---

gdcdictionary/examples/valid/diagnosis.json
gdcdictionary/schemas/diagnosis.yaml

For complete details, see this ticket: https://jira.opensciencedatacloud.org/browse/DICT-54

DICT-54: Updates to the DIAGNOSIS node - YERTLE

---

.gitignore
tests/schema_test.py

the test checks the `links.subgroup` section of `annotation.yaml` to verify that appropriate nodes are linked with annotation nodes

DEV-489 add test for checking links with annotation

---

gdcdictionary/schemas/treatment.yaml
tests/schema_test.py

See updated details in this JIRA Ticket: https://jira.opensciencedatacloud.org/browse/DICT-97

feat/DICT-97: Treatment updates for Boveri release.

---

gdcdictionary/schemas/_terms.yaml

* boveri _terms update - remove special chars & fix typo
* boveri _terms update

chore(sync): sync develop with boveri

---

gdcdictionary/schemas/treatment.yaml

following 2 values were added to pathology_detail.additional_pathology_findings but meant to be added on treatment.treatment_type.
Pleurodesis, Talc
Pleurodesis, NOS

add new treatment_types

---

gdcdictionary/examples/valid/diagnosis.json
gdcdictionary/schemas/_terms.yaml
gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DICT-154

updation of primary_disease property

---

gdcdictionary/schemas/somatic_aggregation_workflow.yaml

https://jira.opensciencedatacloud.org/browse/DICT-171

multiplicity change

---

gdcdictionary/schemas/case.yaml

https://jira.opensciencedatacloud.org/browse/DICT-189

Case Changes - Darwin Release

---

gdcdictionary/schemas/family_history.yaml

https://jira.opensciencedatacloud.org/browse/DICT-232

Updated family history yaml

---

gdcdictionary/schemas/molecular_test.yaml

https://jira.opensciencedatacloud.org/browse/DICT-233

Updated molecular test yaml

---

.gitlab-ci.yml
.pre-commit-config.yaml
README.md
dev-requirements.in
dev-requirements.txt
requirements.txt
setup.py
tox.ini

https://jira.opensciencedatacloud.org/browse/DEV-1672

DEV-1672 automate gdcdatamodel2 generation

---

src/gdcdictionary/schemas/_terms.yaml
src/gdcdictionary/schemas/_terms_enum.yaml

Updates to terms and enum terms YAML files; changes include additions of new enums and property descriptions/references as well as update to URLs for CDE codes to caDSR II browser.

Galileo DICT-314 updates to terms and terms_enum YAMLs

---

src/gdcdictionary/schemas/sample.yaml

https://jira.opensciencedatacloud.org/browse/DICT-306

Galileo - Sample

---

src/gdcdictionary/schemas/masked_methylation_array.yaml

https://jira.opensciencedatacloud.org/browse/DICT-270

Galileo - MaskedMethylationArray

---

src/gdcdictionary/schemas/methylation_beta_value.yaml

https://jira.opensciencedatacloud.org/browse/DICT-269

Galileo - MethylationBetaValue

---

src/gdcdictionary/schemas/raw_methylation_array.yaml

https://jira.opensciencedatacloud.org/browse/DICT-268

Galileo - RawMethylationArray

---

src/gdcdictionary/schemas/case.yaml

https://jira.opensciencedatacloud.org/browse/DICT-313

Galileo - Case

---

src/gdcdictionary/schemas/exposure.yaml

https://jira.opensciencedatacloud.org/browse/DICT-309

Galileo - Exposure

---

src/gdcdictionary/schemas/aligned_reads.yaml

https://jira.opensciencedatacloud.org/browse/DICT-307

Galileo - AlignedReads

---

src/gdcdictionary/schemas/family_history.yaml

https://jira.opensciencedatacloud.org/browse/DICT-310

Galileo - FamilyHistory

---

src/gdcdictionary/schemas/treatment.yaml

https://jira.opensciencedatacloud.org/browse/DICT-312

Galileo - Treatment

---

src/gdcdictionary/schemas/follow_up.yaml

https://jira.opensciencedatacloud.org/browse/DICT-265

Galileo - FollowUp

---

src/gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DICT-264

Galileo - Diagnosis

---

src/gdcdictionary/schemas/demographic.yaml

https://jira.opensciencedatacloud.org/browse/DICT-263

Galileo - Demographic

---

src/gdcdictionary/schemas/_terms.yaml
src/gdcdictionary/schemas/diagnosis.yaml

https://jira.opensciencedatacloud.org/browse/DICT-315

TERMS - typo fixes

---

dev-requirements.txt
requirements.txt

Update dependencies using pip-tools

DEV-1855: run pip compile upgrade

---

.gitlab-ci.yml

create tag from default branch (develop)

DEV 2074 bug fix for tagging

---

src/gdcdictionary/schemas/submitted_aligned_reads.yaml

Updating submitted_aligned_reads node by deprecating enum "scRNA-Seq" for experimental_strategy property 
DICT Jira ticket: https://gdc-ctds.atlassian.net/browse/DICT-335

Updating submitted_aligned_reads node for Inoue DICT-335
