- gdcdictionary/examples/valid/analyte.json
- gdcdictionary/schemas/_terms.yaml
- gdcdictionary/schemas/analyte.yaml
- gdcdictionary/schemas/case.yaml
- gdcdictionary/schemas/copy_number_segment.yaml
- gdcdictionary/schemas/metaschema.yaml
- gdcdictionary/schemas/read_group.yaml
1. We cannot add a non-null constraint for existing fields without (a) verifying all the records have values or (b) populating them. Making instrument_model required for ReadGroup is a breaking schema change that necessitates an update to the data as well, else existing entries will be invalid.
2. The only implementation apparent here is a schema update, however this ticket addresses fields in the data that are not populated.
3. Because of (1), we need to (a) revert this change from develop or (b) populate all instrument_model fields. Due to scope, I am (a) reverting this change in gdcdictionary#190. I intend this ticket to serve as the ticket for applying both schema and data changes moving forward.
The edge label from `copy_number_segment` to `copy_number_liftover_workflows` was changed …
> Revert breaking changes for data release 5

- .travis.yml
- gdcdictionary/python/__init__.py
(cherry picked from commit 6dad7862181135a6db5fc3e558f67f7c75adcc79)
Verified this breaks everything if there's a Unicode char in the schemata (But not in terms or definition files)
> Change GDCDictionary init to bomb out with unicode in schemata files

- gdcdictionary/schemas/clinical_supplement.yaml
https://jira.opensciencedatacloud.org/browse/TT-430
Remove "OMF" enum value from clinical_supplement.data_format
> TT-430: Remove OMF from clinical_supplement.data_format

- gdcdictionary/schemas/project.yaml
https://jira.opensciencedatacloud.org/browse/TT-465
primary_site and disease_type fields were removed from the list of required fields on the project node
> TT-465: Two fields on project node are no longer required

- gdcdictionary/schemas/_terms.yaml
- gdcdictionary/schemas/exposure.yaml
https://jira.opensciencedatacloud.org/browse/TT-383
Second PR for this. We jumped the gun and merged to release/horton without signoff. Here's what was done to get it to this state.
```
gdcdictionary
g fetch #get all the references no objects updated, but now git status knows stuff
g merge-base release/horton origin/release/horton #I know there's a difference
between my local release/horton and what happened on the origin (github)
g show 1119595d78e4b53c7d958beef9669735876fefd9 #merge-base returned this sha
which indicates the most recent common ancestor between release/horton and origin/release/horton
g checkout release/horton
g log # Confirmed that my release/horton branch is pointing to the sha above
g push -f # update orgins reference to my version of release horton (will fail
without …
```
> feat(TT-383) : added new field to exposure node

- gdcdictionary/examples/valid/read_group.json
- gdcdictionary/schemas/read_group.yaml
https://jira.opensciencedatacloud.org/browse/TT-451
The enum value "Hybrid_Selection" was removed from library_selection on node read_group
> TT-451: Removed enum value from read_groups.library_selection

- gdcdictionary/schemas/read_group.yaml
https://jira.opensciencedatacloud.org/browse/TT-453
Remove "RNA_Depletion" enum value from library_selection on node read_group
> TT-453: remove enum value from read_group.library_selection

- gdcdictionary/schemas/read_group.yaml
https://jira.opensciencedatacloud.org/browse/TT-447
Removed "Affinity_Enrichment" from library_selection on node read_group.
> feat/TT-447: removed enum value from read_group.library_selection

- gdcdictionary/schemas/read_group.yaml
https://jira.opensciencedatacloud.org/browse/DAT-1370 
Fixed typo in read_group.target_capture_kit from "TruSeq Amplicon Cancer OncoPanel"  to "TruSeq Amplicon Cancer Panel"
> fix(DAT-1370): fix typo in read_groups.target_capture_kit

- gdcdictionary/schemas/submitted_genomic_profile.yaml
- Relax constraint on submitted genomic profile to read group
from one_to_many to many_to_many
> feat(dictionary): Allow submitted genomic profile link many

- gdcdictionary/tests/schema_test.py
Potential edge case for additional tests. Don't return if the trigger condition is met, which basically means this wouldn't check children nodes in the schema. Not important for the enum test, but future tests may not expect it.
Passed tests locally.
> fix(test): potential error, non traversal of leaves

- setup.py
- Pin pyyaml to 3.11 for release, rolling back bump, we'll fix after oobleck
> chore(pyyaml): Pin pyyaml to 3.11

- gdcdictionary/schemas/molecular_test.yaml
https://jira.opensciencedatacloud.org/browse/DAT-2373
> DAT-2373: new molecular test gene symbols

- tests/schema_test.py
- tests/utils.py
Add a test for cyclic links among the various node types. Ignore the existing bidirectional relationship between file and archive since neither is part of the active graph.
I don't know if we need this, but I thought it might be cool.
> test(cycles): test for cycles

- gdcdictionary/schemas/_terms.yaml
This should the most recent updated _terms file. 
Made changes to script so it treats numbers & system keywords e.g. "yes/no" as reserved & converts to text. added additional missing terms
> updated _terms file generation logic

- gdcdictionary/schemas/molecular_test.yaml
Per request from IMS, we are getting this change in ASAP because it was missed during a release late in 2019. 
Details can be found here: https://jira.opensciencedatacloud.org/browse/DAT-2750
> DAT-2750: Old request for link between slide and molecular_test

- gdcdictionary/python/__init__.py
I tested this by loading the `_terms_enum.yaml` file, which is the largest yaml file in this repo. `safe_load` took just over 7 seconds to complete. Using `CSafeLoader` as the loader took just over 1 second to complete.
`CSafeLoader` can only be imported if libyaml is installed locally. If it still says that `CSafeLoader` cannot be imported then delete the pip wheel cache. The feature is only enabled when pip installs the library, not when the module is imported, which is sort of confusing.
Linux:
```~/.cache/pip```
Mac:
```~/Library/Caches/pip```
Windows:
```%LocalAppData%\pip\Cache```
> feat: use the c library to safeload yaml files

- src/gdcdictionary/schemas/tag.yaml
`exon/common` was removed. Ref must point to tag.
> Update exon ref.

- .gitlab-ci.yml
this PR depends on the following change in gdcdatamodel2: https://github.com/NCI-GDC/gdcdatamodel2/pull/10
> DEV 1740 move release gdcdatamodel2 to gdcdatamodel2

- setup.cfg
Removes non-ascii character from setup.cfg which is preventing installation on VMs
> chore(fix): remove non-ascii character from setup.cfg

- src/gdcdictionary/schemas/read_group.yaml
Updating read_group node to include new enum "Illumina NovaSeq X" for property instrument_model
DICT Jira ticket: https://gdc-ctds.atlassian.net/browse/DICT-339
> Updating read_group node for Inoue DICT-339

- .gitlab-ci.yml
https://gdc-ctds.atlassian.net/browse/DEV-2011
Previously the GitLab pipeline pushes branches to gdcdatamodel2 for new tags from gdcdictionary.
Add this will avoid that.
Tags of gdcdictionary should only push tags for gdcdatamodel2.
> DEV 2011 except tags for push_datamodels_to_github
